
author = "Sergio Abreu García"

[params]
	theme_author = "Sergio Abreu García"
	theme_description = "Minimalist single page theme for Hugo."
	
	description = "This website uses hugo-minimalist-spa theme"