
[params]
	theme_author = "Sergio Abreu García"
	theme_description = "Minimalist single page theme for Hugo."

	author = "Sergio Abreu García"
	description = "This website uses hugo-minimalist-spa theme"